
# supabase/config.toml
project_id = "hwfclxjhrcqnqfwmlmpa"

[api]
enabled_extensions = ["pg_net"]

[auth]
enable_email_autolink = true
enable_phone_autolink = true

[functions.subscribe-newsletter]
# Newsletter subscription function configuration

[functions.soil-analysis]
# Soil analysis AI function
verify_jwt = true

[db]
schemas = ["public", "storage"]

[storage]

[realtime]
