// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwfclxjhrcqnqfwmlmpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3ZmNseGpocmNxbnFmd21sbXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTMzOTcsImV4cCI6MjA2NTQ2OTM5N30.jMPDLuAYAPEMw-_y34By6Yq8GmHsNGBGAiNJMHtwuRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);